### ISSUE TITLE
Facebook authentication is not working

### ISSUE THREAD

**Issue by stephaniejue** [stephaniejue/VolunteerUP#233]
I was able to click allow on facebook, but when it redirects to volunteerup it fails.

![screen shot 2017-02-06 at 10 31 32 am](https://cloud.githubusercontent.com/assets/20118615/22660735/7fe76c00-ec57-11e6-8cb9-be66a02b761b.png)

**Comment by stephaniejue** [comment]
Logs from Heroku

Started GET "/users/auth/facebook" for 108.220.83.21 at 2017-02-06 18:34:22 +0000
2017-02-06T18:34:22.672204+00:00 app[web.1]: I, [2017-02-06T18:34:22.672138 #4]  INFO -- omniauth: (facebook) Request phase initiated.
2017-02-06T18:34:23.007702+00:00 app[web.1]: I, [2017-02-06T18:34:23.007599 #4]  INFO -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45] Started GET "/users/auth/facebook/callback?code=AQCEMhH_xfVW1FCFp98QrhJ0IcIUBisuzauq23lH2N-Ps_GOJaRwkEiE7SKLeenzVGWjP-8w_OjXqssr7R1lba3-JNr2G0XPEGXZqBoA-nzOG96cC2HaKusUQ-QEbWlbwdBT3-BLLf2tbX3S1UkVploCMiC3gnKnl3YBHYW6C3oV4ZPiRHfljDG7NVehm9uJAEaIhpduwbn7BXQIPPE9xiNrtkQG_czXyHMQt7BBfREyAdUmZKsuXi5Cladas9-sU5tTS6-FJbtrQVog-wHoT5HGEo4UzQBCGcM_GRSTUnmW3KB9EjPdizZXWpDtRl0iXMM&state=95a2a4dcf41cf74af614340cc71f89cc7974963d2898bba3" for 108.220.83.21 at 2017-02-06 18:34:23 +0000
2017-02-06T18:34:23.011308+00:00 app[web.1]: I, [2017-02-06T18:34:23.011237 #4]  INFO -- omniauth: (facebook) Callback phase initiated.
2017-02-06T18:34:23.190645+00:00 app[web.1]: I, [2017-02-06T18:34:23.190549 #4]  INFO -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45] Processing by Users::OmniauthCallbacksController#facebook as HTML
2017-02-06T18:34:23.190763+00:00 app[web.1]: I, [2017-02-06T18:34:23.190709 #4]  INFO -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45]   Parameters: {"code"=>"AQCEMhH_xfVW1FCFp98QrhJ0IcIUBisuzauq23lH2N-Ps_GOJaRwkEiE7SKLeenzVGWjP-8w_OjXqssr7R1lba3-JNr2G0XPEGXZqBoA-nzOG96cC2HaKusUQ-QEbWlbwdBT3-BLLf2tbX3S1UkVploCMiC3gnKnl3YBHYW6C3oV4ZPiRHfljDG7NVehm9uJAEaIhpduwbn7BXQIPPE9xiNrtkQG_czXyHMQt7BBfREyAdUmZKsuXi5Cladas9-sU5tTS6-FJbtrQVog-wHoT5HGEo4UzQBCGcM_GRSTUnmW3KB9EjPdizZXWpDtRl0iXMM", "state"=>"95a2a4dcf41cf74af614340cc71f89cc7974963d2898bba3"}
2017-02-06T18:34:23.195287+00:00 app[web.1]: D, [2017-02-06T18:34:23.195231 #4] DEBUG -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45]   User Load (1.4ms)  SELECT  "users".* FROM "users" WHERE "users"."provider" = $1 AND "users"."uid" = $2 ORDER BY "users"."id" ASC LIMIT $3  [["provider", "facebook"], ["uid", "10154095368136793"], ["LIMIT", 1]]
2017-02-06T18:34:23.391161+00:00 app[web.1]: I, [2017-02-06T18:34:23.391051 #4]  INFO -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45] Completed 500 Internal Server Error in 200ms (ActiveRecord: 1.4ms)
2017-02-06T18:34:23.393119+00:00 app[web.1]: F, [2017-02-06T18:34:23.393031 #4] FATAL -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45]   
2017-02-06T18:34:23.393206+00:00 app[web.1]: F, [2017-02-06T18:34:23.393148 #4] FATAL -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45] RuntimeError (redirection forbidden: http://graph.facebook.com/v2.6/10154095368136793/picture -> https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/11953216_10152918611446793_8717484339634798179_n.jpg?oh=c268fc896eaec6142f4b2173af0a52b1&oe=593F64B4):
2017-02-06T18:34:23.393272+00:00 app[web.1]: F, [2017-02-06T18:34:23.393211 #4] FATAL -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45]   
2017-02-06T18:34:23.393336+00:00 app[web.1]: F, [2017-02-06T18:34:23.393275 #4] FATAL -- : [10a04bfc-961f-42bb-b5f7-aaaf4095db45] app/models/user.rb:40:in `block in from_omniauth'
2017-02-06T18:34:23.393337+00:00 app[web.1]: [10a04bfc-961f-42bb-b5f7-aaaf4095db45] app/models/user.rb:36:in `from_omniauth'
2017-02-06T18:34:23.393338+00:00 app[web.1]: [10a04bfc-961f-42bb-b5f7-aaaf4095db45] app/controllers/users/omniauth_callbacks_controller.rb:7:in `all'
2017-02-06T18:34:23.488894+00:00 app[web.1]: I, [2017-02-06T18:34:23.488777 #4]  INFO -- : Finished "/cable/" [WebSocket] for 108.220.83.21 at 2017-02-06 18:34:23 +0000
2017-02-06T18:34:23.490442+00:00 app[web.1]: E, [2017-02-06T18:34:23.490392 #4] ERROR -- : There was an exception - Gem::LoadError(Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded. Add `gem 'redis'` to your Gemfile (and ensure its version is at the minimum required by Action Cable).)
2017-02-06T18:34:23.490613+00:00 app[web.1]: E, [2017-02-06T18:34:23.490546 #4] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/configuration.rb:30:in `rescue in pubsub_adapter'
2017-02-06T18:34:23.490614+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/configuration.rb:27:in `pubsub_adapter'
2017-02-06T18:34:23.490615+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/base.rb:76:in `block in pubsub'
2017-02-06T18:34:23.490615+00:00 app[web.1]: /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
2017-02-06T18:34:23.490616+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/base.rb:76:in `pubsub'
2017-02-06T18:34:23.490616+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/base.rb:52:in `pubsub'
2017-02-06T18:34:23.490617+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/channel/streams.rb:112:in `pubsub'
2017-02-06T18:34:23.490617+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/channel/streams.rb:106:in `block in stop_all_streams'
2017-02-06T18:34:23.490618+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/channel/streams.rb:105:in `each'
2017-02-06T18:34:23.490618+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/channel/streams.rb:105:in `stop_all_streams'
2017-02-06T18:34:23.490619+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
2017-02-06T18:34:23.490619+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:242:in `call'
2017-02-06T18:34:23.490620+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:242:in `block in simple'
2017-02-06T18:34:23.490620+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `call'
2017-02-06T18:34:23.490621+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `block in call'
2017-02-06T18:34:23.490621+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `each'
2017-02-06T18:34:23.490621+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:456:in `call'
2017-02-06T18:34:23.490625+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
2017-02-06T18:34:23.490626+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `call'
2017-02-06T18:34:23.490626+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
2017-02-06T18:34:23.490626+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:81:in `wrap'
2017-02-06T18:34:23.490627+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/engine.rb:66:in `block (3 levels) in <class:Engine>'
2017-02-06T18:34:23.490628+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
2017-02-06T18:34:23.490628+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
2017-02-06T18:34:23.490629+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `call'
2017-02-06T18:34:23.490629+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
2017-02-06T18:34:23.490630+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `call'
2017-02-06T18:34:23.490631+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
2017-02-06T18:34:23.490631+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490632+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490633+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
2017-02-06T18:34:23.490633+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_unsubscribe_callbacks'
2017-02-06T18:34:23.490634+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
2017-02-06T18:34:23.490635+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/channel/base.rb:187:in `unsubscribe_from_channel'
2017-02-06T18:34:23.490636+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/subscriptions.rb:48:in `remove_subscription'
2017-02-06T18:34:23.490637+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/subscriptions.rb:61:in `block in unsubscribe_from_all'
2017-02-06T18:34:23.490640+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/subscriptions.rb:61:in `each'
2017-02-06T18:34:23.490641+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/subscriptions.rb:61:in `unsubscribe_from_all'
2017-02-06T18:34:23.490641+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/base.rb:182:in `handle_close'
2017-02-06T18:34:23.490642+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:58:in `block in invoke'
2017-02-06T18:34:23.490643+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:39:in `block in work'
2017-02-06T18:34:23.490643+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
2017-02-06T18:34:23.490644+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
2017-02-06T18:34:23.490644+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
2017-02-06T18:34:23.490645+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490646+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490646+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
2017-02-06T18:34:23.490647+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `call'
2017-02-06T18:34:23.490647+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
2017-02-06T18:34:23.490648+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `block in with_database_connections'
2017-02-06T18:34:23.490649+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `block in tag'
2017-02-06T18:34:23.490650+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-02-06T18:34:23.490650+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-02-06T18:34:23.490651+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-02-06T18:34:23.490651+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/connection/tagged_logger_proxy.rb:22:in `tag'
2017-02-06T18:34:23.490652+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker/active_record_connection_management.rb:14:in `with_database_connections'
2017-02-06T18:34:23.490653+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
2017-02-06T18:34:23.490654+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `call'
2017-02-06T18:34:23.490654+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
2017-02-06T18:34:23.490655+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `call'
2017-02-06T18:34:23.490656+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
2017-02-06T18:34:23.490657+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490657+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490658+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
2017-02-06T18:34:23.490658+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `call'
2017-02-06T18:34:23.490659+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
2017-02-06T18:34:23.490660+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/engine.rb:60:in `call'
2017-02-06T18:34:23.490661+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/engine.rb:60:in `block (4 levels) in <class:Engine>'
2017-02-06T18:34:23.490661+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
2017-02-06T18:34:23.490662+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/engine.rb:55:in `block (3 levels) in <class:Engine>'
2017-02-06T18:34:23.490662+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
2017-02-06T18:34:23.490666+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
2017-02-06T18:34:23.490667+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `call'
2017-02-06T18:34:23.490667+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
2017-02-06T18:34:23.490668+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `call'
2017-02-06T18:34:23.490669+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
2017-02-06T18:34:23.490669+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490670+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
2017-02-06T18:34:23.490671+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
2017-02-06T18:34:23.490671+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_work_callbacks'
2017-02-06T18:34:23.490672+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
2017-02-06T18:34:23.490672+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:38:in `work'
2017-02-06T18:34:23.490673+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:56:in `invoke'
2017-02-06T18:34:23.490674+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/actioncable-5.0.1/lib/action_cable/server/worker.rb:51:in `block in async_invoke'
2017-02-06T18:34:23.490675+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
2017-02-06T18:34:23.490675+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
2017-02-06T18:34:23.490676+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
2017-02-06T18:34:23.490676+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
2017-02-06T18:34:23.490677+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
2017-02-06T18:34:23.490678+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
2017-02-06T18:34:23.490679+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/concurrent-ruby-1.0.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
2017-02-06T18:34:23.416023+00:00 heroku[router]: at=info method=GET path="/users/auth/facebook/callback?code=AQCEMhH_xfVW1FCFp98QrhJ0IcIUBisuzauq23lH2N-Ps_GOJaRwkEiE7SKLeenzVGWjP-8w_OjXqssr7R1lba3-JNr2G0XPEGXZqBoA-nzOG96cC2HaKusUQ-QEbWlbwdBT3-BLLf2tbX3S1UkVploCMiC3gnKnl3YBHYW6C3oV4ZPiRHfljDG7NVehm9uJAEaIhpduwbn7BXQIPPE9xiNrtkQG_czXyHMQt7BBfREyAdUmZKsuXi5Cladas9-sU5tTS6-FJbtrQVog-wHoT5HGEo4UzQBCGcM_GRSTUnmW3KB9EjPdizZXWpDtRl0iXMM&state=95a2a4dcf41cf74af614340cc71f89cc7974963d2898bba3" host=volunteerup.herokuapp.com request_id=10a04bfc-961f-42bb-b5f7-aaaf4095db45 fwd="108.220.83.21" dyno=web.1 connect=1ms service=390ms status=500 bytes=1669
2017-02-06T18:34:23.488381+00:00 heroku[router]: at=info method=GET path="/cable" host=volunteerup.herokuapp.com request_id=f99483b6-4f74-42b6-ba9d-541c033a1a1e fwd="108.220.83.21" dyno=web.1 connect=1ms service=2980ms status=101 bytes=232
2017-02-06T18:36:17.806597+00:00 heroku[router]: at=info method=GET path="/" host=volunteerup.herokuapp.com request_id=fa418ec5-30d6-41de-9516-984d99a98b11 fwd="108.220.83.21" dyno=web.1 connect=1ms service=34ms status=200 bytes=9016
2017-02-06T18:36:17.773348+00:00 app[web.1]: I, [2017-02-06T18:36:17.773259 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11] Started GET "/" for 108.220.83.21 at 2017-02-06 18:36:17 +0000
2017-02-06T18:36:17.777753+00:00 app[web.1]: I, [2017-02-06T18:36:17.777686 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11] Processing by LandingPageController#index as HTML
2017-02-06T18:36:17.779498+00:00 app[web.1]: I, [2017-02-06T18:36:17.779433 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   Rendering landing_page/index.html.erb within layouts/application
2017-02-06T18:36:17.783461+00:00 app[web.1]: D, [2017-02-06T18:36:17.783387 #4] DEBUG -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   Organization Load (1.4ms)  SELECT "organizations".* FROM "organizations"
2017-02-06T18:36:17.793334+00:00 app[web.1]: D, [2017-02-06T18:36:17.793229 #4] DEBUG -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   User Load (8.3ms)  SELECT "users".* FROM "users"
2017-02-06T18:36:17.800063+00:00 app[web.1]: D, [2017-02-06T18:36:17.799948 #4] DEBUG -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   Event Load (1.7ms)  SELECT "events".* FROM "events"
2017-02-06T18:36:17.801706+00:00 app[web.1]: D, [2017-02-06T18:36:17.801634 #4] DEBUG -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   CACHE (0.0ms)  SELECT "events".* FROM "events"
2017-02-06T18:36:17.802321+00:00 app[web.1]: I, [2017-02-06T18:36:17.802262 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   Rendered landing_page/_counter.html.erb (22.3ms)
2017-02-06T18:36:17.802410+00:00 app[web.1]: I, [2017-02-06T18:36:17.802358 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11]   Rendered landing_page/index.html.erb within layouts/application (22.8ms)
2017-02-06T18:36:17.803800+00:00 app[web.1]: I, [2017-02-06T18:36:17.803742 #4]  INFO -- : [fa418ec5-30d6-41de-9516-984d99a98b11] Completed 200 OK in 26ms (Views: 13.2ms | ActiveRecord: 11.4ms)
2017-02-06T18:36:17.924482+00:00 heroku[router]: at=info method=GET path="/assets/application-6b0edf9ea6becd15f067a95a9b4c2d58cf26f5277711afce02f756651c9b0566.js" host=volunteerup.herokuapp.com request_id=c8fd4ba1-b3a1-4da3-9f57-7e84f2b43da5 fwd="108.220.83.21" dyno=web.1 connect=1ms service=7ms status=200 bytes=122475
2017-02-06T18:36:18.116596+00:00 heroku[router]: at=info method=GET path="/assets/application-c2cfd3994e79a370fbd5664cbe9a802740ddd7c06194fe9f594ae425518e72c8.css" host=volunteerup.herokuapp.com request_id=92353a39-30d8-429e-8c7a-db773dba4751 fwd="108.220.83.21" dyno=web.1 connect=1ms service=2ms status=200 bytes=8706
2017-02-06T18:36:18.562291+00:00 app[web.1]: I, [2017-02-06T18:36:18.562206 #4]  INFO -- : [1985cd33-027d-4179-a7df-7b113f62c3ea] Started GET "/cable" for 108.220.83.21 at 2017-02-06 18:36:18 +0000
2017-02-06T18:36:18.565100+00:00 app[web.1]: I, [2017-02-06T18:36:18.565048 #4]  INFO -- : [1985cd33-027d-4179-a7df-7b113f62c3ea] Started GET "/cable/" [WebSocket] for 108.220.83.21 at 2017-02-06 18:36:18 +0000
2017-02-06T18:36:18.565196+00:00 app[web.1]: I, [2017-02-06T18:36:18.565145 #4]  INFO -- : [1985cd33-027d-4179-a7df-7b113f62c3ea] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
2017-02-06T18:36:18.674787+00:00 app[web.1]: [2017-02-06 18:36:18.674] ERROR -- Specified 'redis' for Action Cable pubsub adapter, but the gem is not loaded. Add `gem 'redis'` to your Gemfile (and ensure its version is at the minimum required by Action Cable).: nil
2017-02-06T18:36:19.004167+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=volunteerup.herokuapp.com request_id=f6d0e1b7-11aa-4de4-aedc-a31e418d1ee3 fwd="108.220.83.21" dyno=web.1 connect=1ms service=1ms status=200 bytes=143
